### ISSUE TITLE
Model is missing for question answer

### ISSUE THREAD

**Issue by sorob** [cassiebreviu/bert-excel-addin-ort-web#1]
Bert model is missing in the repo for question/answer

**Comment by cassiebreviu** [comment]
This model was too large to store in GitHub. I added a link to the tutorial in the readme which has instructions on how to download and export the model from Hugging Face with the Transformers Library. [This is a direct link to the code needed](https://onnxruntime.ai/docs/tutorials/azureml.html#obtain-and-convert-pytorch-model-to-onnx-format).
